# Setup
title:               Blogs by a donki
#tagline:             'Thoughts and Stories'
description:         'An open canvas for me to put my thoughts and stories'
url:                 https://archit-lahiri.github.io
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              Archit Lahiri
#  url:               
  email:             archit.lahiri@gmail.com

# Custom vars
google_analytics_id: #UA-XXXX-Y
